Add features
AeonLucid/POGOLib pull request #97
Opened 2017-07-30 20:24 UTC by Furtif

2017-07-31 00:46 UTC, AeonLucid requested changes

2017-07-31 00:46 UTC, AeonLucid commented on POGOLib.Official/Net/RpcEncryption.cs
> +                return null;
Maybe better to throw an exception because `null` is not expected here.

2017-07-31 00:46 UTC, AeonLucid commented on POGOLib.Official/Util/Hash/PokeHashHasher.cs
> +                        response.Headers.TryGetValues("X-RatePeriodEnd", out ratePeriodEndValue))
Why?

2017-07-31 00:46 UTC, AeonLucid commented on POGOLib.Official/Net/RpcClient.cs
> +        public event EventHandler<CheckAwardedBadgesResponse> CheckAwardedBadgesReceived;
These shouldn't be in `RpcClient`. This class is meant for networking.

2017-07-31 00:46 UTC, AeonLucid commented on POGOLib.Official/Net/RpcClient.cs
> +                // TODO: Using the cells' currenttimestamp gives a delta, which is probably better, but we need to merge the result with the existing ones
This is what I did before but people complained that it was wrong..

2017-07-31 00:46 UTC, AeonLucid commented on POGOLib.Official/Net/RpcClient.cs
> +            if (platformRequest != null)
Why? Request must have a signature.

2017-07-31 00:46 UTC, AeonLucid commented on POGOLib.Official/Net/RpcClient.cs
> +                                if (platformRequest != null)
Why? Request must have a signature.

2017-07-31 01:17 UTC, Furtif commented
I think it's best if I let you see that it will not make you screw up

2017-07-31 01:44 UTC, Furtif commented on POGOLib.Official/Util/Hash/PokeHashHasher.cs
> +                        response.Headers.TryGetValues("X-RatePeriodEnd", out ratePeriodEndValue))
This I do not know well I saw this in another github

2017-07-31 03:39 UTC, Furtif commented on POGOLib.Official/Net/RpcEncryption.cs
> +                return null;
Aff this please :-)

2017-07-31 03:40 UTC, Furtif commented on POGOLib.Official/Net/RpcClient.cs
> +        public event EventHandler<CheckAwardedBadgesResponse> CheckAwardedBadgesReceived;
Change this please :-)

2017-07-31 03:55 UTC, Furtif commented on POGOLib.Official/Net/RpcEncryption.cs
> +                return null;
Add*

2017-07-31 16:08 UTC, Furtif commented on POGOLib.Official/Net/RpcClient.cs
> +        public event EventHandler<CheckAwardedBadgesResponse> CheckAwardedBadgesReceived;
it is needed for https://github.com/AeonLucid/POGOLib/pull/97/files#diff-f9807ab8e1379a13294d996b27e4d204R749

2017-10-06 23:28 UTC, Furtif commented
Merge https://github.com/AeonLucid/POGOProtos/pull/309 update Protos.NetStandard1

2017-10-21 11:32 UTC, PeterDM65 commented
Hi,

After having problems with a previous version of PogoLib since last week (before it worked just fine), i was checking out the latest version of Furtif's developers branch of PogoLib.

Running the following demo program : "POGOLib.Official.Demo.ConsoleApp" after setting the values for "pokeHashAuthKey", "loginProviderStr" (=google), "usernameStr" and "passwordStr", I got the following loggings:


2017-10-21 13:20:09.0579  INFO Booting up.
2017-10-21 13:20:09.1109  INFO Type 'q', 'quit' or 'exit' to exit.
2017-10-21 13:20:10.8024 DEBUG Authenticated through Google.
2017-10-21 13:20:10.8024 DEBUG Session state was set to Stopped.
2017-10-21 13:20:10.8821 DEBUG CheckHasherVersion
2017-10-21 13:20:11.1914  INFO PogoVersion:0.79.3 - Hasher.PokemonVerson:0.79.3 
2017-10-21 13:20:11.1914 DEBUG Session state was set to Started.
2017-10-21 13:20:12.0274 DEBUG Sending RPC Request: 'GetPlayer, CheckChallenge' 
2017-10-21 13:20:12.0274 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-10-21 13:20:12.6126 DEBUG Sending RPC Request: 'GetPlayer, CheckChallenge' 
2017-10-21 13:20:12.6126 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-10-21 13:20:12.8869 DEBUG Received a new AuthTicket from Pokemon!
2017-10-21 13:20:14.0028 DEBUG Sending RPC Request: 'GetMapObjects, CheckChallenge, GetHatchedEggs, GetInventory, CheckAwardedBadges, DownloadSettings, GetInbox'
2017-10-21 13:20:14.0028 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-10-21 13:20:14.1558  INFO Unknown status code: InvalidRequest
2017-10-21 13:20:14.1811 ERROR SendRemoteProcedureCall exception: System.Exception: There were 0 responses.
   at POGOLib.Official.Net.RpcClient.HandleResponseEnvelope(RequestEnvelope requestEnvelope, ResponseEnvelope responseEnvelope) in D:\Gebruikers\Peter\Downloads\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib.Official\Net\RpcClient.cs:line 688
   at POGOLib.Official.Net.RpcClient.<PerformRemoteProcedureCallAsync>d__41.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib.Official\Net\RpcClient.cs:line 663
2017-10-21 13:20:14.2463 ERROR Map refresh failed: System.NullReferenceException: response
   at POGOLib.Official.Net.RpcClient.<RefreshMapObjectsAsync>d__33.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib.Official\Net\RpcClient.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at POGOLib.Official.Pokemon.HeartbeatDispatcher.<Dispatch>d__7.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib.Official\Pokemon\HeartbeatDispatcher.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at POGOLib.Official.Pokemon.HeartbeatDispatcher.<CheckDispatch>d__4.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib-ec3b6129adb1ecf5a37d5a45917e4eedd382f642\POGOLib.Official\Pokemon\HeartbeatDispatcher.cs:line 73
2017-10-21 13:20:14.2463  INFO No fort found nearby.

And this is exactly the same problem with the previous version.
What went wrong ? 
The RPC Request "GetPlayer" is oké, I see my player stats. But it crashes afterwards ...

2017-10-21 13:09 UTC, Furtif commented
Pogolib into nuguets is outed ... Check source of this current pr or try m’y core branch

2017-10-21 14:41 UTC, PeterDM65 commented
Thnx for the response,
but ... 
I downloaded as zip your source code @ "https://github.com/Furtif/POGOLib/tree/core"
and run again the demo programm "POGOLib.Core.Demo.ConsoleApp" (after changing the hashkey, username, password of course).
And got the same logging (Unknown status code : InvalidRequest)

2017-10-21 16:34:45.8713  INFO Booting up.
2017-10-21 16:34:45.9252  INFO Type 'q', 'quit' or 'exit' to exit.
2017-10-21 16:34:58.0824 DEBUG Authenticated through Google.
2017-10-21 16:34:58.0824 DEBUG Session state was set to Stopped.
2017-10-21 16:35:08.8814 DEBUG Session state was set to Started.
2017-10-21 16:35:10.0218 DEBUG Sending RPC Request: 'GetPlayer, CheckChallenge' 
2017-10-21 16:35:10.0218 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-10-21 16:35:10.5968 DEBUG Sending RPC Request: 'GetPlayer, CheckChallenge' 
2017-10-21 16:35:10.5968 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-10-21 16:35:10.8348 DEBUG Received a new AuthTicket from Pokemon!
2017-10-21 16:35:11.8351 DEBUG Sending RPC Request: 'GetMapObjects, CheckChallenge, GetHatchedEggs, GetInventory, CheckAwardedBadges, DownloadSettings, GetInbox'
2017-10-21 16:35:11.8351 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-10-21 16:35:12.0620  INFO Unknown status code: InvalidRequest
2017-10-21 16:35:12.0883 ERROR SendRemoteProcedureCall exception: System.Exception: There were 0 responses.
   at POGOLib.Official.Net.RpcClient.HandleResponseEnvelope(RequestEnvelope requestEnvelope, ResponseEnvelope responseEnvelope) in D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs:line 687
   at POGOLib.Official.Net.RpcClient.<PerformRemoteProcedureCallAsync>d__41.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs:line 662
2017-10-21 16:35:12.1538 ERROR Map refresh failed: System.NullReferenceException: response
   at POGOLib.Official.Net.RpcClient.<RefreshMapObjectsAsync>d__33.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at POGOLib.Official.Pokemon.HeartbeatDispatcher.<Dispatch>d__7.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Pokemon\HeartbeatDispatcher.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at POGOLib.Official.Pokemon.HeartbeatDispatcher.<CheckDispatch>d__4.MoveNext() in D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Pokemon\HeartbeatDispatcher.cs:line 73
2017-10-21 16:35:35.8067  INFO No fort found nearby.

2017-10-21 14:48 UTC, Furtif commented
you uses a valid key hash ??

2017-10-21 14:51 UTC, PeterDM65 commented
Yes,
It's a new one, and the request for "GetPlayer" seems to work ...

2017-10-21 14:52 UTC, Furtif commented
ok check procedures

- GYM_GET_INFO replaces GET_GYM_DETAILS (*need edition after merge)
- GET_HOLO_INVENTORY  replaces GET_INVENTORY  (*need edition after merge)
- GYM_START_SESSION replaces START_GYM_BATTLE  (*need edition after merge)
- GYM_BATTLE_ATTACK replaces ATTACK_GYM (*need edition after merge)

```*Maybe```

2017-10-21 14:59 UTC, PeterDM65 commented
Yes ... that seems to do it

I replaced "RequestType.GetInventory" by "RequestType.GetHoloInventory" and the demo program 
worked at following places

Find all "GetInventory", Subfolders, Find Results 1, Entire Solution, ""
  D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs(59):            RequestType.GetInventory,
  D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs(363):                    RequestType = RequestType.GetInventory,
  D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs(364):                    RequestMessage = new GetInventoryMessage
  D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs(763):                    case RequestType.GetInventory: // Get_Inventory
  D:\Gebruikers\Peter\Downloads\POGOLib-core\POGOLib-core\POGOLib.Core\Net\RpcClient.cs(764):                        var inventory = GetInventoryResponse.Parser.ParseFrom(bytes);
  C:\Users\Peter\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\682D9FC3-A62C-4079-BDE9-7C5EE24C0FCB\c3\c0a60562\RequestType.cs(102):    [OriginalName("GET_INVENTORY")] GetInventory = 5005,
  Matching lines: 6    Matching files: 2    Total files searched: 53

Thanx very much !!!!!

2017-10-21 15:15 UTC, Furtif commented
@PeterDM65 fixed get inventory redownload sources.

2017-11-10 22:16 UTC, PeterDM65 commented
@Furtif: I downloaded your latest version of the pogolib at https://github.com/Furtif/POGOLib (core branch). When running the demo program "POGOLib.Core.Demo.ConsoleApp" I got the following errors:
2017-11-10 23:14:29.5564  INFO Booting up.
2017-11-10 23:14:29.6058  INFO Type 'q', 'quit' or 'exit' to exit.
2017-11-10 23:14:30.0941 DEBUG Authenticated from cache.
2017-11-10 23:14:30.0981 DEBUG Session state was set to Stopped.
2017-11-10 23:14:30.6565 DEBUG Session state was set to Started.
2017-11-10 23:14:31.0189 DEBUG Sending RPC Request: 'GetPlayer, CheckChallenge'
2017-11-10 23:14:31.0229 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-11-10 23:14:31.6145 DEBUG Sending RPC Request: 'GetPlayer, CheckChallenge'
2017-11-10 23:14:31.6145 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-11-10 23:14:31.9333 DEBUG Received a new AuthTicket from Pokemon!
2017-11-10 23:14:33.0361 DEBUG Sending RPC Request: 'GetMapObjects, CheckChallenge, GetHatchedEggs, GetHoloInventory, CheckAwardedBadges, DownloadSettings, GetInbox, GetInbox'
2017-11-10 23:14:33.0361 DEBUG => Platform Request: 'SendEncryptedSignature, UnknownPtr8'
2017-11-10 23:14:33.2178  INFO Unknown status code: SessionInvalidated
2017-11-10 23:14:33.2448 ERROR SendRemoteProcedureCall exception: System.Exception: There were 0 responses.
   at POGOLib.Official.Net.RpcClient.HandleResponseEnvelope(RequestEnvelope requestEnvelope, ResponseEnvelope responseEnvelope) in L:\Gebruikers\Peter\Mijn documenten\Visual Studio 2017\Projects\PoGo.App\PogoLib\Furtif\POGOLib-core\POGOLib.Core\Net\RpcClient.cs:line 706
   at POGOLib.Official.Net.RpcClient.<PerformRemoteProcedureCallAsync>d__41.MoveNext() in L:\Gebruikers\Peter\Mijn documenten\Visual Studio 2017\Projects\PoGo.App\PogoLib\Furtif\POGOLib-core\POGOLib.Core\Net\RpcClient.cs:line 681
2017-11-10 23:14:33.3099 ERROR Map refresh failed: System.NullReferenceException: response
   at POGOLib.Official.Net.RpcClient.<RefreshMapObjectsAsync>d__33.MoveNext() in L:\Gebruikers\Peter\Mijn documenten\Visual Studio 2017\Projects\PoGo.App\PogoLib\Furtif\POGOLib-core\POGOLib.Core\Net\RpcClient.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at POGOLib.Official.Pokemon.HeartbeatDispatcher.<Dispatch>d__7.MoveNext() in L:\Gebruikers\Peter\Mijn documenten\Visual Studio 2017\Projects\PoGo.App\PogoLib\Furtif\POGOLib-core\POGOLib.Core\Pokemon\HeartbeatDispatcher.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at POGOLib.Official.Pokemon.HeartbeatDispatcher.<CheckDispatch>d__4.MoveNext() in L:\Gebruikers\Peter\Mijn documenten\Visual Studio 2017\Projects\PoGo.App\PogoLib\Furtif\POGOLib-core\POGOLib.Core\Pokemon\HeartbeatDispatcher.cs:line 73
2017-11-10 23:14:33.3099  INFO No fort found nearby.

2017-11-10 23:01 UTC, Furtif commented
@PeterDM65 ok try again i m changed to old mode getmapobjects

2017-11-10 23:11 UTC, PeterDM65 commented
Works now ... thnx

2018-04-11 07:49 UTC, closed without merging